"use client";

import {useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {Activity, KeyRound, LoaderCircle, LogOut, Save, ShieldCheck, Trash2} from "lucide-react";
import {useRouter} from "next/navigation";
import {useState} from "react";
import {toast} from "sonner";
import {ConfirmDeleteDialog} from "@/components/confirm-delete-dialog";
import {MetricCell} from "@/components/dashboard";
import {PageHeader} from "@/components/page-header";
import {StatusBadge} from "@/components/status-badge";
import {Button} from "@/components/ui/button";
import {ErrorState} from "@/components/ui/error-state";
import {Input} from "@/components/ui/input";
import {LoadingState} from "@/components/ui/loading-state";
import {apiFetch, authFetch} from "@/lib/api";
import type {AuthSession, Organization, QuotaUsage, User} from "@/lib/types";
import {initials, relativeTime} from "@/lib/utils";

export default function ProfilePage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [name, setName] = useState<string | null>(null); const [email, setEmail] = useState<string | null>(null); const [password, setPassword] = useState(""); const [organizationId, setOrganizationId] = useState<string | null>(null);
  const user = useQuery({queryKey: ["me"], queryFn: () => apiFetch<User>("/auth/me")});
  const organizations = useQuery({queryKey: ["organizations"], queryFn: () => apiFetch<Organization[]>("/organizations/")});
  const sessions = useQuery({queryKey: ["auth-sessions"], queryFn: () => apiFetch<AuthSession[]>("/auth/sessions")});
  const quota = useQuery({queryKey: ["quota", "me"], queryFn: () => apiFetch<QuotaUsage>("/quotas/me")});
  const effectiveName = name ?? user.data?.full_name ?? ""; const effectiveEmail = email ?? user.data?.email ?? ""; const effectiveOrganizationId = organizationId ?? user.data?.organization_id ?? "";
  const save = useMutation({mutationFn: () => apiFetch<User>("/auth/me", {method: "PATCH", body: JSON.stringify({full_name: effectiveName, email: effectiveEmail, organization_id: effectiveOrganizationId, ...(password ? {password} : {})})}), onSuccess: async () => {setName(null); setEmail(null); setOrganizationId(null); setPassword(""); await Promise.all([queryClient.invalidateQueries({queryKey: ["me"]}), queryClient.invalidateQueries({queryKey: ["auth-sessions"]})]); toast.success("Profile updated");}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to update profile")});
  const revoke = useMutation({mutationFn: (sessionId: string) => apiFetch(`/auth/sessions/${sessionId}`, {method: "DELETE"}), onSuccess: async () => {await queryClient.invalidateQueries({queryKey: ["auth-sessions"]}); toast.success("Session revoked");}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to revoke session")});
  const removeAccount = useMutation({mutationFn: () => apiFetch<{deleted_projects: number}>("/auth/me", {method: "DELETE"}), onSuccess: async () => {await authFetch("/logout").catch(() => undefined); router.replace("/login"); router.refresh();}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to delete account")});
  if (user.isLoading) return <LoadingState label="Loading profile" rows={6} />;
  if (user.isError || !user.data) return <ErrorState title="Profile could not be loaded" description="The current-user endpoint returned an error." onRetry={() => void user.refetch()} />;
  const daily = quota.data ? `${quota.data.daily_used}/${quota.data.policy.daily_run_limit}` : "—";
  const monthly = quota.data ? `${quota.data.monthly_used}/${quota.data.policy.monthly_run_limit}` : "—";

  return <div className="mx-auto max-w-5xl space-y-6"><PageHeader eyebrow="Settings" title="Profile & access" description="Manage identity, organization context, durable sessions, execution quota, and account lifecycle." />
    <div className="grid gap-5 md:grid-cols-[220px_1fr]"><aside className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5 text-center"><span className="mx-auto flex size-16 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-xl font-semibold text-[var(--accent-hover)]">{initials(user.data.full_name, user.data.email)}</span><h2 className="mt-4 text-sm font-semibold">{user.data.full_name || "CCSR user"}</h2><p className="mt-1 break-all text-[9px] text-[var(--ink-muted)]">{user.data.email}</p><div className="mt-4 flex items-center justify-center gap-1.5 text-[9px] capitalize text-[var(--accent)]"><ShieldCheck className="size-3" />{user.data.global_role}</div></aside><form onSubmit={(event) => {event.preventDefault(); save.mutate();}} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-medium">Full name</span><Input value={effectiveName} onChange={(event) => setName(event.target.value)} /></label><label><span className="mb-2 block text-xs font-medium">Email</span><Input type="email" value={effectiveEmail} onChange={(event) => setEmail(event.target.value)} /></label><label><span className="mb-2 block text-xs font-medium">Organization</span><select value={effectiveOrganizationId} onChange={(event) => setOrganizationId(event.target.value)} className="h-10 w-full rounded-lg border border-[var(--border)] bg-[var(--surface-muted)] px-3 text-sm"><option value="">Personal workspace</option>{organizations.data?.map((organization) => <option key={organization.organization_id} value={organization.organization_id}>{organization.name}</option>)}</select></label><label><span className="mb-2 block text-xs font-medium">New password <span className="font-normal text-[var(--ink-muted)]">(optional)</span></span><Input type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 8 characters" /></label></div><div className="mt-6 flex justify-end"><Button type="submit" disabled={save.isPending || !effectiveEmail || (password.length > 0 && password.length < 8)}>{save.isPending ? <LoaderCircle className="size-4 animate-spin" /> : <Save className="size-4" />}Save profile</Button></div></form></div>

    <section className="overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] p-4"><h2 className="text-sm font-semibold">Execution quota</h2><p className="mt-1 text-[10px] text-[var(--ink-muted)]">Durable usage reservations enforced by the workflow gateway.</p></div>{quota.isError ? <div className="p-4"><ErrorState title="Quota unavailable" description="Current quota usage could not be loaded." onRetry={() => void quota.refetch()} /></div> : <div className="grid grid-cols-2 md:grid-cols-4"><MetricCell label="Daily runs" value={daily} icon={Activity} /><MetricCell label="Monthly runs" value={monthly} icon={Activity} /><MetricCell label="Active runs" value={quota.data?.active_runs ?? "—"} icon={LoaderCircle} /><MetricCell label="Concurrent limit" value={quota.data?.policy.concurrent_run_limit ?? "—"} icon={ShieldCheck} /></div>}</section>

    <section className="overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] p-4"><h2 className="text-sm font-semibold">Authenticated sessions</h2><p className="mt-1 text-[10px] text-[var(--ink-muted)]">Revoke access on devices you no longer use.</p></div>{sessions.isLoading ? <LoadingState label="Loading sessions" rows={3} /> : sessions.isError ? <div className="p-4"><ErrorState title="Sessions unavailable" description="The session registry could not be loaded." onRetry={() => void sessions.refetch()} /></div> : <div className="divide-y divide-[var(--border)]">{sessions.data?.map((session) => <div key={session.session_id} className="flex items-center gap-3 p-4"><span className="flex size-9 items-center justify-center rounded-lg bg-[var(--surface-2)] text-[var(--accent)]"><KeyRound className="size-4" /></span><div className="min-w-0 flex-1"><p className="font-mono text-[10px] text-[var(--ink-secondary)]">{session.session_id}</p><p className="mt-1 text-[9px] text-[var(--ink-muted)]">Created {relativeTime(session.created_at)} · expires {new Date(session.expires_at).toLocaleDateString()}</p></div>{session.current ? <StatusBadge status="current" /> : session.revoked_at ? <StatusBadge status="revoked" /> : <Button variant="ghost" size="sm" disabled={revoke.isPending} onClick={() => revoke.mutate(session.session_id)}><LogOut className="size-3.5" />Revoke</Button>}</div>)}</div>}</section>

    <section className="rounded-xl border border-[var(--danger-border)] bg-[var(--danger-soft)] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-[var(--danger-soft-text)]">Delete account</h2><p className="mt-1 max-w-2xl text-[10px] leading-5 text-[var(--ink-muted)]">Permanently revoke sessions and remove owned projects through registered capability cleanup hooks.</p></div><Button variant="secondary" className="text-[var(--danger)]" onClick={() => setDeleteOpen(true)}><Trash2 className="size-4" />Delete account</Button></div></section>
    <ConfirmDeleteDialog open={deleteOpen} name={user.data.email} title="Delete your account?" consequences="All active sessions will be revoked and projects you own will be deleted through capability lifecycle cleanup. This cannot be undone." isPending={removeAccount.isPending} onClose={() => setDeleteOpen(false)} onConfirm={() => removeAccount.mutate()} />
  </div>;
}
