"use client";

import {useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {Building2, Copy, LoaderCircle, MailPlus, Pencil, Plus, Trash2, UserPlus, XCircle} from "lucide-react";
import {useState} from "react";
import {toast} from "sonner";
import {ConfirmDeleteDialog} from "@/components/confirm-delete-dialog";
import {PageHeader} from "@/components/page-header";
import {Button} from "@/components/ui/button";
import {Dialog} from "@/components/ui/dialog";
import {EmptyState} from "@/components/ui/empty-state";
import {ErrorState} from "@/components/ui/error-state";
import {Input} from "@/components/ui/input";
import {LoadingState} from "@/components/ui/loading-state";
import {apiFetch} from "@/lib/api";
import type {Organization, OrganizationInvitation, User} from "@/lib/types";
import {relativeTime} from "@/lib/utils";

export default function OrganizationPage() {
  const queryClient = useQueryClient();
  const [editing, setEditing] = useState<Organization | "new" | null>(null);
  const [deleting, setDeleting] = useState<Organization | null>(null);
  const [name, setName] = useState("");
  const [selectedOrganizationId, setSelectedOrganizationId] = useState<string | null>(null);
  const [inviteEmail, setInviteEmail] = useState("");
  const [inviteRole, setInviteRole] = useState<"member" | "admin">("member");
  const [inviteToken, setInviteToken] = useState("");
  const [createdToken, setCreatedToken] = useState<string | null>(null);
  const organizations = useQuery({queryKey: ["organizations"], queryFn: () => apiFetch<Organization[]>("/organizations/")});
  const user = useQuery({queryKey: ["me"], queryFn: () => apiFetch<User>("/auth/me")});
  const invitations = useQuery({queryKey: ["organization-invitations", selectedOrganizationId], queryFn: () => apiFetch<OrganizationInvitation[]>(`/organizations/${selectedOrganizationId}/invitations`), enabled: Boolean(selectedOrganizationId)});
  const save = useMutation({mutationFn: () => editing === "new" ? apiFetch<Organization>("/organizations/", {method: "POST", body: JSON.stringify({name})}) : apiFetch<Organization>(`/organizations/${editing?.organization_id}`, {method: "PATCH", body: JSON.stringify({name})}), onSuccess: async () => {await queryClient.invalidateQueries({queryKey: ["organizations"]}); setEditing(null); setName(""); toast.success("Organization saved");}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to save organization")});
  const remove = useMutation({mutationFn: (id: string) => apiFetch(`/organizations/${id}`, {method: "DELETE"}), onSuccess: async () => {await queryClient.invalidateQueries({queryKey: ["organizations"]}); setDeleting(null); toast.success("Organization deleted");}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to delete organization")});
  const invite = useMutation({mutationFn: () => apiFetch<OrganizationInvitation>(`/organizations/${selectedOrganizationId}/invitations`, {method: "POST", body: JSON.stringify({email: inviteEmail, role: inviteRole})}), onSuccess: async (result) => {setCreatedToken(result.invitation_token ?? null); setInviteEmail(""); await queryClient.invalidateQueries({queryKey: ["organization-invitations", selectedOrganizationId]}); toast.success("Invitation created");}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to create invitation")});
  const revoke = useMutation({mutationFn: (invitationId: string) => apiFetch(`/organizations/${selectedOrganizationId}/invitations/${invitationId}`, {method: "DELETE"}), onSuccess: async () => {await queryClient.invalidateQueries({queryKey: ["organization-invitations", selectedOrganizationId]}); toast.success("Invitation revoked");}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to revoke invitation")});
  const accept = useMutation({mutationFn: () => apiFetch<Organization>(`/organizations/invitations/${encodeURIComponent(inviteToken.trim())}/accept`, {method: "POST"}), onSuccess: async (organization) => {setInviteToken(""); await Promise.all([queryClient.invalidateQueries({queryKey: ["organizations"]}), queryClient.invalidateQueries({queryKey: ["me"]})]); toast.success(`Joined ${organization.name}`);}, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to accept invitation")});
  function open(value: Organization | "new") {setEditing(value); setName(value === "new" ? "" : value.name);}
  return <div className="mx-auto max-w-5xl space-y-6"><PageHeader eyebrow="Account" title="Organization settings" description="Create and rename organizations, then choose your active organization from the application top bar." actions={<Button onClick={() => open("new")}><Plus className="size-4" />New organization</Button>} />
    {organizations.isLoading ? <LoadingState label="Loading organizations" rows={3} /> : organizations.isError ? <ErrorState title="Organizations could not be loaded" description="The authenticated organization API returned an error." onRetry={() => void organizations.refetch()} /> : organizations.data?.length ? <div className="overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)]">{organizations.data.map((organization) => <article key={organization.organization_id} className="flex flex-col gap-4 border-b border-[var(--border)] p-4 last:border-0 sm:flex-row sm:items-center"><span className="flex size-10 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Building2 className="size-5" /></span><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{organization.name}</h2><p className="mono mt-1 truncate text-[8px] text-[var(--ink-disabled)]">{organization.organization_id}</p><p className="mt-1 text-[9px] text-[var(--ink-muted)]">Updated {relativeTime(organization.updated_at)}{user.data?.organization_id === organization.organization_id ? " · Active" : ""}</p></div><div className="flex flex-wrap gap-1"><Button variant="ghost" size="sm" onClick={() => {setSelectedOrganizationId(organization.organization_id); setCreatedToken(null);}}><UserPlus className="size-3.5" />Invitations</Button><Button variant="ghost" size="sm" onClick={() => open(organization)}><Pencil className="size-3.5" />Rename</Button><Button variant="ghost" size="sm" className="text-[var(--danger)]" onClick={() => setDeleting(organization)}><Trash2 className="size-3.5" />Delete</Button></div></article>)}</div> : <EmptyState icon={Building2} title="No organizations yet" description="Projects can remain in your personal workspace, or you can create an organization." action="Create organization" onAction={() => open("new")} />}

    <section className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center gap-2"><MailPlus className="size-4 text-[var(--accent)]" /><h2 className="text-sm font-semibold">Accept an invitation</h2></div><p className="mt-2 text-[10px] text-[var(--ink-muted)]">Paste the one-time invitation token provided by an organization owner or admin.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><Input value={inviteToken} onChange={(event) => setInviteToken(event.target.value)} placeholder="Invitation token" /><Button disabled={!inviteToken.trim() || accept.isPending} onClick={() => accept.mutate()}>{accept.isPending ? <LoaderCircle className="size-4 animate-spin" /> : <UserPlus className="size-4" />}Accept invitation</Button></div></section>
    <Dialog open={Boolean(editing)} onClose={() => setEditing(null)} title={editing === "new" ? "Create organization" : "Rename organization"} description="Organization names can be changed without affecting project vector collections."><label className="mt-5 block"><span className="mb-2 block text-xs font-medium">Organization name</span><Input value={name} onChange={(event) => setName(event.target.value)} /></label><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button disabled={name.trim().length < 2 || save.isPending} onClick={() => save.mutate()}>{save.isPending ? <LoaderCircle className="size-4 animate-spin" /> : null}Save organization</Button></div></Dialog>
    <Dialog open={Boolean(selectedOrganizationId)} onClose={() => setSelectedOrganizationId(null)} title="Organization invitations" description="Invite members or organization admins. Invitation tokens are shown only when created."><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_130px_auto]"><Input type="email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} placeholder="researcher@example.com" /><select value={inviteRole} onChange={(event) => setInviteRole(event.target.value as "member" | "admin")} className="h-10 rounded-lg border border-[var(--border)] bg-[var(--surface-muted)] px-3 text-sm"><option value="member">Member</option><option value="admin">Admin</option></select><Button disabled={!inviteEmail.includes("@") || invite.isPending} onClick={() => invite.mutate()}>{invite.isPending ? <LoaderCircle className="size-4 animate-spin" /> : <Plus className="size-4" />}Invite</Button></div>{createdToken ? <div className="mt-4 rounded-lg border border-[var(--accent-border)] bg-[var(--accent-soft)] p-3"><p className="text-[10px] text-[var(--ink-secondary)]">Copy this token now; it is not returned again.</p><button className="mt-2 flex w-full items-center gap-2 break-all rounded-md bg-[var(--background)] p-2 text-left font-mono text-[9px] text-[var(--accent-hover)]" onClick={() => void navigator.clipboard.writeText(createdToken)}><Copy className="size-3.5 shrink-0" />{createdToken}</button></div> : null}<div className="mt-5 divide-y divide-[var(--border)] border-t border-[var(--border)]">{invitations.isLoading ? <LoadingState label="Loading invitations" rows={2} /> : invitations.data?.map((item) => <div key={item.invitation_id} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{item.email}</p><p className="mt-1 text-[9px] capitalize text-[var(--ink-muted)]">{item.role} · {item.status} · expires {new Date(item.expires_at).toLocaleDateString()}</p></div>{item.status === "pending" ? <Button variant="ghost" size="sm" className="text-[var(--danger)]" disabled={revoke.isPending} onClick={() => revoke.mutate(item.invitation_id)}><XCircle className="size-3.5" />Revoke</Button> : null}</div>)}{!invitations.isLoading && !invitations.data?.length ? <p className="py-6 text-center text-xs text-[var(--ink-muted)]">No invitations yet.</p> : null}</div></Dialog>
    {deleting ? <ConfirmDeleteDialog open name={deleting.name} title={`Delete ${deleting.name}?`} consequences="The organization record will be soft-deleted. The current API does not return an impact preview for users or projects, so verify dependencies before continuing." isPending={remove.isPending} onClose={() => setDeleting(null)} onConfirm={() => remove.mutate(deleting.organization_id)} /> : null}
  </div>;
}
